In [16]:
import os
import pandas as pd
import numpy as np
import pickle
from pathlib import Path

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
pd.options.display.max_rows = None

In [17]:

# raw_dir = Path.cwd().parent / "data" / "raw"

# credits_dir = raw_dir / "credits.csv"
# keywords_dir = raw_dir / "keywords.csv"
# links_small_dir = raw_dir / "links_small.csv"
# links_dir = raw_dir / "links.csv"
# movie_metadata_dir = raw_dir / "movies_metadata.csv"
# ratings_small_dir = raw_dir / "ratings_small.csv"
# rating_dir = raw_dir / "ratings.csv"

In [18]:
# # unuseful csv
# # links_small = pd.read_csv(links_small_dir)

# # useful csv
# movie_metadata = pd.read_csv(movie_metadata_dir)
# credits = pd.read_csv(credits_dir)
# keywords = pd.read_csv(keywords_dir)
# links = pd.read_csv(links_dir)


# ratings_small = pd.read_csv(ratings_small_dir)
# rating = pd.read_csv(rating_dir)

In [ ]:
# collab
raw_dir = Path.cwd()

credits_dir = raw_dir / "credits.csv"
keywords_dir = raw_dir / "keywords.csv"
links_small_dir = raw_dir / "links_small.csv"
links_dir = raw_dir / "links.csv"
movie_metadata_dir = raw_dir / "movies_metadata.csv"
ratings_small_dir = raw_dir / "ratings_small.csv"
rating_dir = raw_dir / "ratings.csv"

movie_metadata = pd.read_csv(movie_metadata_dir, low_memory=False)
# credits = pd.read_csv(credits_dir)
keywords = pd.read_csv(keywords_dir)
links = pd.read_csv(links_dir)
# ratings_small = pd.read_csv(ratings_small_dir)
rating = pd.read_csv(rating_dir)

In [ ]:
# print(credits.info())
print("-"*100)
print(movie_metadata.info())
print("-"*100)
print(keywords.info())
print("-"*100)
# print(ratings_small.info())
print("-"*100)
print(rating.info())

----------------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB
None
----------------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  object
dtypes: int64(1), object(1)
memory usage: 725.4+ KB
None
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2989237 entries, 0 to 2989236
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  float64
dtypes: float64(2), int64(2)
memory usage: 91.2 MB
None

In [ ]:
movie_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [ ]:
movie_metadata.drop(columns = ["belongs_to_collection" , "homepage" , "budget" , "poster_path" , "status" , "tagline" , "video"] , inplace = True)

In [ ]:
movie_metadata.info()
# fill the na values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   adult                 45466 non-null  object
 1   genres                45466 non-null  object
 2   id                    45466 non-null  object
 3   imdb_id               45449 non-null  object
 4   original_language     45455 non-null  object
 5   original_title        45466 non-null  object
 6   overview              44512 non-null  object
 7   popularity            45461 non-null  object
 8   production_companies  45463 non-null  object
 9   production_countries  45463 non-null  object
 10  release_date          45379 non-null  object
 11  revenue               45460 non-null  float64
 12  runtime               45203 non-null  float64
 13  spoken_languages      45460 non-null  object
 14  title                 45460 non-null  object
 15  vote_average          45460 non-null  float64
 16  vote_count            45460 non-null  float64
dtypes: float64(4), object(13)
memory usage: 5.9+ MB

In [24]:
# @title
missing_imdb_id_rows = movie_metadata[movie_metadata['imdb_id'].isnull()]
display(missing_imdb_id_rows[['id', 'original_title', 'imdb_id']])

           id                                     original_title imdb_id
8966    36337                                           Delusion     NaN
13757  200796                                               Show     NaN
13821   75015  Jak rozpętałem drugą wojnę światową: Cz.3 - Wś...     NaN
17382   36663                                        Dreamkiller     NaN
17510   47116                                              Víťaz     NaN
18959   28500       Before The Dinosaurs - Walking With Monsters     NaN
19322  118013                                          Endeavour     NaN
20806   15257                                 Hulk vs. Wolverine     NaN
20937   55576                          Last Stand at Saber River     NaN
21916  293412                                       Running Wild     NaN
22987   45514                                                  8     NaN
23744   30146                          トップをねらえ！＆トップをねらえ２！合体劇場版!!     NaN
33753  324017                                         The Master     NaN
36955  161535                                     Doraemon:貓狗時空傳     NaN
40809   65256                     H2O Just Add Water - The Movie     NaN
41832  430514                                  Le passe-muraille     NaN
45070  439314                     The Garden of Afflictions 2017     NaN

As you can see, there are a few rows where `imdb_id` is missing. For now, I will fill the missing `imdb_id` values with an empty string, but depending on your specific use case, you might consider dropping these rows or using another unique identifier if available and appropriate.

In [ ]:
# @title
movie_metadata['imdb_id'].fillna('', inplace=True)
print(f"Number of null values in 'imdb_id' after filling: {movie_metadata['imdb_id'].isnull().sum()}")

Number of null values in 'imdb_id' after filling: 0

/tmp/ipykernel_1119/4238391292.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_metadata['imdb_id'].fillna('', inplace=True)

In [ ]:
# @title
import ast

def get_primary_spoken_language_iso(languages_str):
    """Extracts the ISO_639_1 code of the first spoken language from the spoken_languages string."""
    if pd.isna(languages_str) or languages_str == '[]':
        return None
    try:
        languages = ast.literal_eval(languages_str)
        if languages and isinstance(languages, list) and 'iso_639_1' in languages[0]:
            return languages[0]['iso_639_1']
    except (ValueError, SyntaxError):
        pass # Handle cases where string is not a valid list representation
    return None

# Create a temporary column with primary spoken language ISO codes
movie_metadata['primary_spoken_language_iso'] = movie_metadata['spoken_languages'].apply(get_primary_spoken_language_iso)

# Fill missing original_language values using the temporary column
# Only apply to rows where original_language is NaN
movie_metadata['original_language'].fillna(movie_metadata['primary_spoken_language_iso'], inplace=True)

# Drop the temporary column
movie_metadata.drop(columns=['primary_spoken_language_iso'], inplace=True)

print(f"Number of null values in 'original_language' after filling: {movie_metadata['original_language'].isnull().sum()}")
print(movie_metadata[movie_metadata.original_language.isna()][['original_title', 'spoken_languages', 'original_language']])

Number of null values in 'original_language' after filling: 0
Empty DataFrame
Columns: [original_title, spoken_languages, original_language]
Index: []

/tmp/ipykernel_1119/2740915553.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_metadata['original_language'].fillna(movie_metadata['primary_spoken_language_iso'], inplace=True)

In [ ]:
movie_metadata.overview.head()[1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures."

In [ ]:
movie_metadata[movie_metadata.overview.isna()]
# i have to solve this using gen ai using gemini llm

       adult                                             genres      id  \
32     False  [{'id': 10749, 'name': 'Romance'}, {'id': 12, ...   78802
300    False  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...  161495
634    False                     [{'id': 35, 'name': 'Comedy'}]  287305
635    False                     [{'id': 35, 'name': 'Comedy'}]  339428
641    False                     [{'id': 35, 'name': 'Comedy'}]   10801
644    False                      [{'id': 18, 'name': 'Drama'}]  278978
679    False  [{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...  117730
792    False                                                 []  281085
802    False                      [{'id': 18, 'name': 'Drama'}]  282919
821    False                                                 []   48144
832    False                                                 []  145925
863    False                   [{'id': 53, 'name': 'Thriller'}]  253632
1022   False                      [{'id': 18, 'name': 'Drama'}]  108365
1076   False  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...  146341
1389   False  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...   43775
1410   False                     [{'id': 35, 'name': 'Comedy'}]   60083
2140   False                                                 []   77314
2194   False                                                 []  134368
4130   False  [{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...  109472
4752   False                     [{'id': 35, 'name': 'Comedy'}]   78657
4796   False  [{'id': 35, 'name': 'Comedy'}, {'id': 10769, '...   58886
5951   False                     [{'id': 35, 'name': 'Comedy'}]   29224
6008   False                                                 []   81346
6236   False  [{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...   61939
8558   False                                                 []   65048
8987   False                                                 []   53688
9171   False                                                 []  175739
9421   False  [{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...  100594
9623   False                      [{'id': 18, 'name': 'Drama'}]   32546
10004  False  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...  113178
10607  False                      [{'id': 18, 'name': 'Drama'}]   55396
10690  False                                                 []   68646
11602  False  [{'id': 35, 'name': 'Comedy'}, {'id': 10769, '...   52920
11968  False                                                 []  155386
12934  False                     [{'id': 35, 'name': 'Comedy'}]   22554
13211  False                      [{'id': 18, 'name': 'Drama'}]   47499
13562  False                                                 []   55748
13565  False                                                 []   55500
13576  False                     [{'id': 35, 'name': 'Comedy'}]   61070
13655  False                                                 []  156908
13660  False                     [{'id': 35, 'name': 'Comedy'}]  210487
13667  False                     [{'id': 35, 'name': 'Comedy'}]   38869
13721  False                     [{'id': 35, 'name': 'Comedy'}]  155426
13757  False  [{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...  200796
13763  False  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...   64968
13805  False                                                 []  156917
14009  False  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...   66949
14027  False  [{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...  128856
14067  False                                                 []  154430
14091  False                                                 []   41427
14123  False  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  140887
14129  False                     [{'id': 35, 'name': 'Comedy'}]   18120
14184  False                                                 []   63615
14529  False  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...   63764
14629  False  [{'id': 35, 'name': 'Comedy'}, {'id': 37, 'nam...  147683
14669  False                     [{'id': 35, 'name': 'Comedy'}]  148435
14688  False  [{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...  144089
14746  False  [{'id': 80, 'name': 'Crime'}, {'id': 37, 'name...  147692
14769  False  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   62775
14870  False                     [{'id': 35, 'name': 'Comedy'}]  120280
14889  False                      [{'id': 18, 'name': 'Drama'}]  117499
14890  False                                                 []  174748
15204  False                                                 []   21245
15205  False                      [{'id': 18, 'name': 'Drama'}]   60677
15245  False                                                 []  173865
15330  False  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...   30695
15384  False                                                 []   46341
15733  False                                                 []   55403
15842  False  [{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...   74714
15991  False                                                 []   90930
16009  False  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...  370264
16111  False                                                 []  157178
16119  False                      [{'id': 18, 'name': 'Drama'}]   72421
16631  False                                                 []   71732
16633  False                      [{'id': 18, 'name': 'Drama'}]  116751
16659  False                      [{'id': 18, 'name': 'Drama'}]   65898
16661  False                                                 []  102527
16662  False                                                 []  148432
16854  False                                                 []   53364
16876  False                      [{'id': 18, 'name': 'Drama'}]   81414
16901  False                                                 []   54354
17012  False                      [{'id': 18, 'name': 'Drama'}]   72375
17023  False  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...    4880
17096  False                                                 []   55408
17154  False                                                 []  145154
17179  False                     [{'id': 35, 'name': 'Comedy'}]    3962
17180  False  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...  142712
17192  False  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   74183
17271  False                                                 []   55763
17274  False                                                 []   55761
17317  False                                                 []   55754
17325  False                                                 []  148314
17338  False                      [{'id': 18, 'name': 'Drama'}]  289010
17348  False                                                 []   55756
17349  False                     [{'id': 35, 'name': 'Comedy'}]   55759
17414  False                      [{'id': 18, 'name': 'Drama'}]  177697
17458  False                [{'id': 99, 'name': 'Documentary'}]  404479
17462  False                                                 []   55166
17490  False                      [{'id': 18, 'name': 'Drama'}]  230680
17597  False                     [{'id': 35, 'name': 'Comedy'}]   92465
17644  False  [{'id': 10402, 'name': 'Music'}, {'id': 99, 'n...  105287
17817  False                                                 []  132227
17862  False                                                 []   72419
17951  False                                                 []  434973
18023  False  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...   86126
18038  False                                                 []  344741
18047  False                                                 []   62614
18056  False                      [{'id': 18, 'name': 'Drama'}]   61121
18343  False  [{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...   74878
18372  False  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...  162374
18393  False  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...  145594
18402  False                     [{'id': 35, 'name': 'Comedy'}]   31337
18572  False                [{'id': 99, 'name': 'Documentary'}]  404471
18573  False                                                 []   79362
18598  False  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...  247500
18657  False  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...   85883
18672  False                                                 []  399229
18854  False  [{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...   86727
18916  False  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...   61361
18968  False                      [{'id': 18, 'name': 'Drama'}]  362151
19126  False                                                 []   78999
19269  False  [{'id': 10752, 'name': 'War'}, {'id': 18, 'nam...  116019
19315  False  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  458428
19358  False  [{'id': 99, 'name': 'Documentary'}, {'id': 12,...  110491
19371  False                      [{'id': 18, 'name': 'Drama'}]   79034
19380  False  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...   35623
19451  False  [{'id': 12, 'name': 'Adventure'}, {'id': 35, '...  112973
19478  False  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...   76703
19701  False                [{'id': 99, 'name': 'Documentary'}]  262988
19831  False                      [{'id': 18, 'name': 'Drama'}]  156180
19833  False                     [{'id': 35, 'name': 'Comedy'}]   62012
19874  False                      [{'id': 18, 'name': 'Drama'}]  328712
19908  False                     [{'id': 35, 'name': 'Comedy'}]   26152
19934  False  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...  128637
19951  False  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   64362
20117  False  [{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...  177522
20147  False                     [{'id': 35, 'name': 'Comedy'}]   72678
20148  False                     [{'id': 35, 'name': 'Comedy'}]   57307
20166  False                                                 []  139909
20257  False                                                 []  128644
20332  False                                                 []   76686
20379  False           [{'id': 878, 'name': 'Science Fiction'}]  334317
20601  False                [{'id': 99, 'name': 'Documentary'}]   81225
20629  False  [{'id': 10770, 'name': 'TV Movie'}, {'id': 18,...  134806
20642  False                [{'id': 99, 'name': 'Documentary'}]   62130
20684  False                                                 []  131822
20686  False                                                 []  142989
20711  False                                                 []   54356
20778  False                                                 []  149469
20788  False  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...   65646
20826  False                                                 []   55524
20851  False                      [{'id': 18, 'name': 'Drama'}]   82662
20958  False                   [{'id': 53, 'name': 'Thriller'}]   38875
21102  False                [{'id': 99, 'name': 'Documentary'}]  388046
21152  False                     [{'id': 35, 'name': 'Comedy'}]   67272
21160  False  [{'id': 10402, 'name': 'Music'}, {'id': 18, 'n...   83342
21242  False                                                 []   60824
21250  False                                                 []  173914
21436  False  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...   65958
21499  False  [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...  217038
21744  False                     [{'id': 35, 'name': 'Comedy'}]   77776
21763  False  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  161073
21820  False  [{'id': 28, 'name': 'Action'}, {'id': 10769, '...   19623
21894  False                [{'id': 99, 'name': 'Documentary'}]  153196
21919  False                [{'id': 99, 'name': 'Documentary'}]   82627
21984  False  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   52045
22313  False                                                 []  430985
22337  False                                                 []   85469
22346  False  [{'id': 9648, 'name': 'Mystery'}, {'id': 80, '...  388182
22350  False  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...  130233
22424  False                                                 []  267219
22488  False                      [{'id': 18, 'name': 'Drama'}]  110992
22543  False  [{'id': 53, 'name': 'Thriller'}, {'id': 10769,...   81600
22546  False  [{'id': 9648, 'name': 'Mystery'}, {'id': 80, '...   91380
22549  False                     [{'id': 35, 'name': 'Comedy'}]  101352
22573  False                     [{'id': 35, 'name': 'Comedy'}]  297560
22584  False                     [{'id': 35, 'name': 'Comedy'}]  331958
22591  False                                                 []   52150
22663  False  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...  216369
22747  False                     [{'id': 35, 'name': 'Comedy'}]  172890
22756  False  [{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...   52147
22776  False                     [{'id': 35, 'name': 'Comedy'}]  246320
22806  False                [{'id': 99, 'name': 'Documentary'}]   32547
22807  False                                                 []  219931
22818  False  [{'id': 28, 'name': 'Action'}, {'id': 878, 'na...  418029
22852  False                                                 []  142984
22870  False                     [{'id': 35, 'name': 'Comedy'}]  204765
22989  False                     [{'id': 35, 'name': 'Comedy'}]   68827
22999  False  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...  116894
23024  False  [{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...   55825
23038  False                      [{'id': 18, 'name': 'Drama'}]  394403
23226  False                                                 []  202183
23418  False  [{'id': 10770, 'name': 'TV Movie'}, {'id': 18,...  272543
23420  False                                                 []  173151
23733  False                     [{'id': 27, 'name': 'Horror'}]  206574
23814  False  [{'id': 9648, 'name': 'Mystery'}, {'id': 35, '...   60106
23829  False                                                 []  164419
23853  False                     [{'id': 35, 'name': 'Comedy'}]   44155
23874  False                     [{'id': 35, 'name': 'Comedy'}]   64934
24023  False  [{'id': 10402, 'name': 'Music'}, {'id': 18, 'n...   74950
24036  False                [{'id': 99, 'name': 'Documentary'}]    2692
24044  False                     [{'id': 35, 'name': 'Comedy'}]   76846
24063  False                [{'id': 99, 'name': 'Documentary'}]  329227
24137  False  [{'id': 16, 'name': 'Animation'}, {'id': 10751...  343693
24177  False  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...  182799
24230  False                     [{'id': 35, 'name': 'Comedy'}]  230295
24244  False                     [{'id': 35, 'name': 'Comedy'}]   42416
24527  False  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...  273510
24626  False                     [{'id': 35, 'name': 'Comedy'}]   12076
25006  False                     [{'id': 35, 'name': 'Comedy'}]  204768
25087  False                     [{'id': 35, 'name': 'Comedy'}]  117678
25088  False  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  129966
25089  False                     [{'id': 35, 'name': 'Comedy'}]  198130
25203  False  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...  204965
25306  False                [{'id': 99, 'name': 'Documentary'}]  151730
25346  False                                                 []  124207
25348  False                                                 []   42438
25361  False                                                 []   56971
25363  False                     [{'id': 35, 'name': 'Comedy'}]   42441
25364  False  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...   38366
25365  False                     [{'id': 35, 'name': 'Comedy'}]  121510
25373  False                     [{'id': 35, 'name': 'Comedy'}]   48935
25502  False                     [{'id': 35, 'name': 'Comedy'}]  205349
25504  False  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...  285532
25507  False  [{'id': 35, 'name': 'Comedy'}, {'id': 28, 'nam...  255906
25510  False                                                 []   52238
25511  False                                                 []  165159
25513  False                                                 []  127760
25514  False                     [{'id': 35, 'name': 'Comedy'}]   62725
25557  False  [{'id': 10770, 'name': 'TV Movie'}, {'id': 35,...  212503
25561  False                                                 []  307113
25567  False                    [{'id': 37, 'name': 'Western'}]  129062
25587  False                  [{'id': 10751, 'name': 'Family'}]  302118
25630  False                                                 []   55553
25677  False                     [{'id': 35, 'name': 'Comedy'}]  197335
25678  False                     [{'id': 35, 'name': 'Comedy'}]   82341
25682  False                     [{'id': 35, 'name': 'Comedy'}]   48805
25805  False                     [{'id': 35, 'name': 'Comedy'}]  128946
25906  False                     [{'id': 35, 'name': 'Comedy'}]   59040
25909  False  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   56825
25910  False                                                 []   60014
25911  False                                                 []   56551
25912  False                                                 []   58189
25914  False                                                 []   58081
25915  False                     [{'id': 35, 'name': 'Comedy'}]   42674
25918  False                                                 []   43544
25922  False  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   93855
25925  False                     [{'id': 35, 'name': 'Comedy'}]  255456
25929  False                                                 []  211710
25937  False                     [{'id': 35, 'name': 'Comedy'}]  251555
26074  False  [{'id': 10770, 'name': 'TV Movie'}, {'id': 18,...  269165
26132  False                      [{'id': 18, 'name': 'Drama'}]    3539
26134  False                                                 []   80472
26145  False  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  211179
26284  False                     [{'id': 35, 'name': 'Comedy'}]  241982
26292  False                                                 []  129359
26438  False  [{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...   30028
26596  False  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...   58757
26700  False                                                 []   79892
26873  False                     [{'id': 35, 'name': 'Comedy'}]   10639
27073  False  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  145194
27310  False                     [{'id': 35, 'name': 'Comedy'}]   11719
27413  False  [{'id': 10752, 'name': 'War'}, {'id': 18, 'nam...  168300
27475  False                                                 []  131503
27520  False                                                 []  123283
27571  False                [{'id': 99, 'name': 'Documentary'}]   58587
27587  False  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...   72917
27594  False  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   76642
27597  False                     [{'id': 35, 'name': 'Comedy'}]   64357
27601  False                                                 []  157787
27652  False                   [{'id': 53, 'name': 'Thriller'}]  102534
27695  False                     [{'id': 35, 'name': 'Comedy'}]   30149
27702  False                      [{'id': 18, 'name': 'Drama'}]   28573
27880  False                                                 []  226163
27883  False                                                 []   57342
27947  False                      [{'id': 18, 'name': 'Drama'}]   62352

In [ ]:
movie_metadata[movie_metadata.popularity.isna()]

,adult,genres,id,imdb_id,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,title,vote_average,vote_count
19729,False,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",82663,tt0113002,en,Midnight Man,British soldiers force a recently captured IRA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19730,- Written by Ørnås,"[{'name': 'Carousel Productions', 'id': 11176}...",1997-08-20,0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,False,6.0,1,NaN,NaN,NaN,NaN,NaN,NaN
29502,False,"[{'id': 16, 'name': 'Animation'}, {'id': 878, ...",122662,tt2423504,ja,マルドゥック・スクランブル 排気,Third film of the Mardock Scramble series.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29503,Rune Balot goes to a casino connected to the ...,"[{'name': 'Aniplex', 'id': 2883}, {'name': 'Go...",2012-09-29,0,68.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,False,7.0,12,NaN,NaN,NaN,NaN,NaN,NaN
35586,False,"[{'id': 10770, 'name': 'TV Movie'}, {'id': 28,...",249260,tt2622826,en,Avalanche Sharks,A group of skiers are terrorized during spring...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
missing_percentage = movie_metadata.isnull().sum() * 100 / len(movie_metadata)
print("Percentage of missing values per column in movie_metadata:\n")
print(missing_percentage.sort_values(ascending=False))

Percentage of missing values per column in movie_metadata:

overview                2.098271
runtime                 0.578454
release_date            0.191352
spoken_languages        0.013197
vote_count              0.013197
title                   0.013197
revenue                 0.013197
vote_average            0.013197
popularity              0.010997
production_countries    0.006598
production_companies    0.006598
adult                   0.000000
original_title          0.000000
genres                  0.000000
id                      0.000000
imdb_id                 0.000000
original_language       0.000000
dtype: float64

In [ ]:
movie_metadata.dropna(subset=['original_title'], inplace=True)
print(f"Number of rows after dropping NaNs in 'title': {len(movie_metadata)}")

Number of rows after dropping NaNs in 'title': 45466

In [ ]:
display(movie_metadata[movie_metadata.isnull().any(axis=1)])

                                                   adult  \
32                                                 False
300                                                False
634                                                False
635                                                False
641                                                False
644                                                False
679                                                False
711                                                False
734                                                False
792                                                False
802                                                False
821                                                False
832                                                False
863                                                False
1022                                               False
1076                                               False
1389                                               False
1410                                               False
2140                                               False
2194                                               False
3460                                               False
3628                                               False
4130                                               False
4752                                               False
4796                                               False
5879                                               False
5951                                               False
6008                                               False
6236                                               False
8558                                               False
8987                                               False
9171                                               False
9421                                               False
9623                                               False
10004                                              False
10607                                              False
10690                                              False
11602                                              False
11968                                              False
12934                                              False
13211                                              False
13562                                              False
13565                                              False
13576                                              False
13655                                              False
13660                                              False
13667                                              False
13721                                              False
13757                                              False
13763                                              False
13805                                              False
13839                                              False
14009                                              False
14027                                              False
14067                                              False
14091                                              False
14123                                              False
14129                                              False
14184                                              False
14529                                              False
14629                                              False
14669                                              False
14688                                              False
14746                                              False
14769                                              False
14801                                              False
14870                                              False
14889                                              False
14890                                              False
15204                                              False
15205                                              False
15245                                              False
15330                                              False
15384                                              False
15733                                              False
15842                                              False
15991                                              False
16009                                              False
16111                                              False
16119                                              False
16631                                              False
16633                                              False
16659                                              False
16661                                              False
16662                                              False
16836                                              False
16854                                              False
16876                                              False
16901                                              False
16953                                              False
17012                                              False
17023                                              False
17096                                              False
17154                                              False
17179                                              False
17180                                              False
17192                                              False
17271                                              False
17274                                              False
17317                                              False
17325                                              False
17338                                              False
17339                                              False
17348                                              False
17349                                              False
17382                                              False
17414                                              False
17458                                              False
17462                                              False
17490                                              False
17597                                              False
17644                                              False
17817                                              False
17862                                              False
17951                                              False
18023                                              False
18038                                              False
18047                                              False
18056                                              False
18343                                              False
18362                                              False
18372                                              False
18393                                              False
18402                                              False
18572                                              False
18573                                              False
18598                                              False
18657                                              False
18672                                              False
18854                                              False
18916                                              False
18968                                              False
19126                                              False
19269                                              False
19315                                              False
19322                                              False
19358                                              False
19371                                              False
19380                                              False
19451                                              False
19478                                              False
19701                                              False
19729                                              False
19730                                 - Written by Ørnås
19831                                              False
19833                                              False
19874                                              False
19908                                              False
19934                                              False
19951                                              False
19955                                              False
20103                                              False
20117                                              False
20147                                              False
20148                                              False
20166                                              False
20257                                              False
20301                                              False
20332                                              False
20379                                              False
20601                                              False
20629                                              False
20631                                              False
20642                                              False
20684                                              False
20686                                              False
20711                                              False
20778                                              False
20788                                              False
20826                                              False
20851                                              False
20958                                              False
21102                                              False
21152                                              False
21160                                              False
21167                                              False
21242                                              False
21250                                              False
21436                                              False
21499                                              False
21708                                              False
21744                                              False
21763                                              False
21820                                              False
21894                                              False
21919                                              False
21957                                              False
21984                                              False
22019                                              False
22313                                              False
22337                                              False
22346                                              False
22350                                              False
22424                                              False
22488                                              False
22543                                              False
22546                                              False
22549                                              False
22573                                              False
22584                                              False
22591                                              False
22663                                              False
22747                                              False
22756                                              False
22776                                              False
22798                                              False
22806                                              False
22807                                              False
22818                                              False
22852                                              False
22870                                              False
22989                                              False
22999                                              False
23024                                              False
23038                                              False
23226                                              False
23418                                              False
23420                                              False
23733                                              False
23814                                              False
23829                                              False
23853                                              False
23874                                              False
24023                                              False
24036                                              False
24044                                              False
24050                                              False
24063                                              False
24137                                              False
24157                                              False
24177                                              False
24230                                              False
24244                                              False
24527                                              False
24626                                              False
24738                                              False
25006                                              False
25087                                              False
25088                                              False
25089                                              False
25203                                              False
25306                                              False
25346                                              False
25348                                              False
25361                                              False
25363                                              False
25364                                              False
25365                                              False
25373                                              False
25502                                              False
25504                                              False
25507                                              False
25510                                              False
25511                                              False
25513                                              False
25514                                              False
25557                                              False
25561                                              False
25567                                              False
25587                                              False
25630                                              False
25677                                              False
25678                                              False
25682                                              False
25805                                              False
25906                                              False
25909                                              False
25910                                              False
25911                                              False
25912                                              False
25914                                              False
25915                                              False
25918                                              False
25922                                              False
25925                                              False
25929                                              False
25937                                              False
26074                                              False
26132                                              False
26134                                              False
26145                                              False
26284                                              False
26292                                              False
26438                                              False
26596                                              False
26700                                              False
26873                                              False
27073                                              False
27310                                              False
27413                                              False
27475                                              False
27499                                              False
27520                                              False
27571                                              False
27587                                              False
27594                                              False
27597                                              False
27601                                              False
27652                                              False
27695                                              False
27702                                              False
27880                                              False
27883                                              False
27947                                              False
27967                                              False
28132                                              False
28245                                              False
28267                                              False
28269                                              False
28271                                              False
28273                                              False
28276                                              False
28280                                              False
28282                                              False
28364                                              False
28386                                              False
28387                                              False
28415                                              False
28471                                              False
28473                                              False
28484                                              False
28493                                              False
28510                                              False
28549                                              False
28550                                              False
28604                                              False
28657                                              False
28658                                              False
28800                                              False
28918                                              False
28951                                              False
28964                                              False
28973                                              False
28982                                              False
28983                                              False
28985                                              False
29152                                              False
29227                                              False
29264                                              False
29295                                              False
29300                                              False
29307                                              False
29308                                              False
29309                                              False
29311                                              False
29382                                              False
29395                                              False
29418                                              False
29448                                              False

In [ ]:
# movie_metadata[movie_metadata.revenue.isna()]

movie_metadata.dropna(subset=['revenue'], inplace=True)

In [ ]:
#Impute with the median runtime:
median_runtime = movie_metadata['runtime'].median()
movie_metadata['runtime'].fillna(median_runtime, inplace=True)
print(f"Number of null values in 'runtime' after median imputation: {movie_metadata['runtime'].isnull().sum()}")


display(movie_metadata[movie_metadata.runtime.isnull()])

/tmp/ipykernel_1119/780946598.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_metadata['runtime'].fillna(median_runtime, inplace=True)

Number of null values in 'runtime' after median imputation: 0

Empty DataFrame
Columns: [adult, genres, id, imdb_id, original_language, original_title, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, title, vote_average, vote_count]
Index: []

In [ ]:
movie_metadata.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45460 entries, 0 to 45465
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   adult                 45460 non-null  object
 1   genres                45460 non-null  object
 2   id                    45460 non-null  object
 3   imdb_id               45460 non-null  object
 4   original_language     45460 non-null  object
 5   original_title        45460 non-null  object
 6   overview              44506 non-null  object
 7   popularity            45460 non-null  object
 8   production_companies  45460 non-null  object
 9   production_countries  45460 non-null  object
 10  release_date          45376 non-null  object
 11  revenue               45460 non-null  float64
 12  runtime               45460 non-null  float64
 13  spoken_languages      45460 non-null  object
 14  title                 45460 non-null  object
 15  vote_average          45460 non-null  float64
 16  vote_count            45460 non-null  float64
dtypes: float64(4), object(13)
memory usage: 6.2+ MB

In [ ]:
# revenue is not useful in my case
movie_metadata.drop(columns=['revenue'] , inplace = True)

In [ ]:
pd.DataFrame({"original_title" : movie_metadata.original_title , "title" : movie_metadata.title})
# due to both series are same but different languges in original_title based on contry publised so i can drop the original_title

movie_metadata.drop(columns=['original_title'] , inplace = True)

In [ ]:
movie_metadata.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45460 entries, 0 to 45465
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   adult                 45460 non-null  object
 1   genres                45460 non-null  object
 2   id                    45460 non-null  object
 3   imdb_id               45460 non-null  object
 4   original_language     45460 non-null  object
 5   overview              44506 non-null  object
 6   popularity            45460 non-null  object
 7   production_companies  45460 non-null  object
 8   production_countries  45460 non-null  object
 9   release_date          45376 non-null  object
 10  runtime               45460 non-null  float64
 11  spoken_languages      45460 non-null  object
 12  title                 45460 non-null  object
 13  vote_average          45460 non-null  float64
 14  vote_count            45460 non-null  float64
dtypes: float64(3), object(12)
memory usage: 5.5+ MB

In [ ]:
movie_metadata.head()

,adult,genres,id,imdb_id,original_language,overview,popularity,production_companies,production_countries,release_date,runtime,spoken_languages,title,vote_average,vote_count
0,False,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,tt0114709,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Toy Story,7.7,5415.0
1,False,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,tt0113497,en,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Jumanji,6.9,2413.0
2,False,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,tt0113228,en,A family wedding reignites the ancient feud be...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Grumpier Old Men,6.5,92.0
3,False,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,tt0114885,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Waiting to Exhale,6.1,34.0
4,False,"[{'id': 35, 'name': 'Comedy'}]",11862,tt0113041,en,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Father of the Bride Part II,5.7,173.0

In [ ]:
%pip install langgraph langchain  pydantic google-genai langchain-google-genai

Requirement already satisfied: langgraph in /usr/local/lib/python3.12/dist-packages (1.0.10)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (2.12.3)
Requirement already satisfied: google-genai in /usr/local/lib/python3.12/dist-packages (1.66.0)
Collecting langchain-google-genai
  Downloading langchain_google_genai-4.2.1-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: langchain-core>=0.1 in /usr/local/lib/python3.12/dist-packages (from langgraph) (1.2.17)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langgraph) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (0.3.9)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.4.2)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (4.12.1)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai) (2.47.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (2.32.4)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (15.0.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai) (1.3.1)
Collecting filetype<2.0.0,>=1.2.0 (from langchain-google-genai)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.1->langgraph) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.1->langgraph) (0.7.13)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.1->langgraph) (26.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.1->langgraph) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.1->langgraph) (0.14.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph) (3.11.7)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.5.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core>=0.1->langgraph) (3.0.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core>=0.1->langgraph) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core>=0.1->langgraph) (0.25.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (0.6.2)
Downloading langchain_google_genai-4.2.1-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 2.2 MB/s eta 0:00:00
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Installing collected packages: filetype, langchain-google-genai
Successfully installed filetype-1.2.0 langchain-google-genai-4.2.1

In [ ]:
%pip install langchain-google-genai

Requirement already satisfied: langchain-google-genai in /usr/local/lib/python3.12/dist-packages (4.2.1)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai) (1.2.0)
Requirement already satisfied: google-genai<2.0.0,>=1.56.0 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai) (1.66.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.5 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai) (1.2.17)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai) (2.12.3)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (4.12.1)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (2.47.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (2.32.4)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (1.3.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (0.7.13)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (26.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (0.14.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (0.25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (2.5.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.6.2)

In [49]:
from langgraph.graph import StateGraph , START , END
from langchain_google_genai import ChatGoogleGenerativeAI
from typing import TypedDict , Optional
from dotenv import load_dotenv
from langchain_core.output_parsers import StrOutputParser

load_dotenv()

False

In [ ]:
model = ChatGoogleGenerativeAI(model = "gemini-2.5-flash-lite")

ValidationError: 1 validation error for ChatGoogleGenerativeAI
  Value error, API key required for Gemini Developer API. Provide api_key parameter or set GOOGLE_API_KEY/GEMINI_API_KEY environment variable. [type=value_error, input_value={'model': 'gemini-2.5-fla...te', 'model_kwargs': {}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

In [ ]:
movie_metadata.to_csv("movies_after_nan.csv")